version: "3"

services:
  mongodb:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      
  nest:
    build:
      context: ./siemens-test-back/
      dockerfile: ./dockerfile
    ports:
      - 3003:3003
    env_file:
      - ./.env

  angular:
    build:
      context: ./siemens-test-front/
      dockerfile: ./dockerfile
    env_file:
      - ./.env
    ports:
      - 80:80

volumes:
  mongodb_data_container:
